---
vmauth:
  enabled: false
vminsert:
  enabled: true
  extraArgs:
    maxLabelsPerTimeseries: "50"
  fullnameOverride: 'victoria-metrics-insert'
  replicaCount: 2
  podDisruptionBudget:
    enabled: true
    maxUnavailable: 1
vmselect:
  enabled: true
  extraArgs:
    search.maxQueryLen: "5MB"
  fullnameOverride: 'victoria-metrics-select'
  replicaCount: 1
  mode: statefulSet
  persistentVolume:
    enabled: true
    size: 4Gi
  podDisruptionBudget:
    enabled: true
    maxUnavailable: 1
vmstorage:
  enabled: true
  fullnameOverride: 'victoria-metrics-storage'
  persistentVolume:
    enabled: true
    name: storage
    size: 32Gi
  replicaCount: 1
  retentionPeriod: 30d
