---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  namespace: "linkerd"
  name: "linkerd"
spec:
  provider:
    aws:
      service: SecretsManager
      region: "us-west-2"
      auth:
        jwt:
          serviceAccountRef:
            name: "linkerd-secret-store"
