---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: "linkerd"
  name: "linkerd-secret-store"
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::472882997329:role/pg02-eso-linkerd"
