---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  namespace: "cert-manager"
  name: "cert-manager-helm-values"
spec:
  interval: 10m
  prune: true
  sourceRef:
    kind: GitRepository
    namespace: flux-system
    name: flux-system
  path: "/manifests/cert-manager/cert-manager-helm-values"
  targetNamespace: "cert-manager"
  healthChecks:
  - apiVersion: v1
    kind: ConfigMap
    namespace: "cert-manager"
    name: "cert-manager-helm-values"
