---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cert-manager-namespace.yaml
- cert-manager-certificate.yaml
- cert-manager-cluster-issuer.yaml
- cert-manager-helm-release.yaml
- cert-manager-helm-repository.yaml
- cert-manager-helm-values.yaml
