---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  namespace: "kubenuts"
  name: "external-secrets"
spec:
  interval: 30m
  timeout: 10m
  releaseName: "external-secrets"
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        namespace: "kubenuts"
        name: "external-secrets"
      chart: external-secrets
      version: "2.9.0"
  install:
    crds: CreateReplace
    remediation:
      retries: 10
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 10
  valuesFrom:
  - kind: ConfigMap
    name: "external-secrets-helm-values"
    valuesKey: values.yaml
