---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  namespace: "kubenuts"
  name: "weave-gitops"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: "kubenuts"
  target:
    name: "weave-gitops"
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: "pg02/kubenuts/weave-gitops/admin-username"
  - secretKey: passwordHash
    remoteRef:
      key: "pg02/kubenuts/weave-gitops/admin-password-hash"
