---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  namespace: "victoria-metrics"
  name: "victoria-metrics-operator-helm-values"
spec:
  interval: 10m
  prune: true
  sourceRef:
    kind: GitRepository
    namespace: flux-system
    name: flux-system
  path: "/manifests/victoria-metrics/victoria-metrics-operator-helm-values"
  targetNamespace: "victoria-metrics"
  healthChecks:
  - apiVersion: v1
    kind: ConfigMap
    namespace: "victoria-metrics"
    name: "victoria-metrics-operator-helm-values"
