---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  namespace: "victoria-metrics"
  name: "victoria-metrics"
spec:
  interval: 3h
  url: https://victoriametrics.github.io/helm-charts/
