---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  namespace: "argocd"
  name: "argocd-secret"
  labels:
    app.kubernetes.io/name: "argocd-secret"
    app.kubernetes.io/part-of: "argocd"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: "argocd"
  target:
    name: "argocd-secret"
    creationPolicy: Owner
    template:
      engineVersion: v2
      mergePolicy: Merge
  data:
    - secretKey: admin.password
      remoteRef:
        key: "pg02/argocd/argocd-secret"
        property: admin-password-hash
    - secretKey: admin.passwordMtime
      remoteRef:
        key: "pg02/argocd/argocd-secret"
        property: admin-password-mtime
    - secretKey: server.secretkey
      remoteRef:
        key: "pg02/argocd/argocd-secret"
        property: server-secret-key
