---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  namespace: "kubenuts"
  name: "weave-gitops-secrets"
spec:
  dependsOn:
  - namespace: "kubenuts"
    name: "kubenuts-secret-store"
  interval: 10m
  prune: true
  sourceRef:
    kind: GitRepository
    namespace: flux-system
    name: flux-system
  path: "/manifests/weave-gitops/weave-gitops-secrets"
  targetNamespace: "kubenuts"
  healthChecks:
  - apiVersion: external-secrets.io/v1
    kind: ExternalSecret
    namespace: "kubenuts"
    name: "weave-gitops"
  - apiVersion: v1
    kind: Secret
    namespace: "kubenuts"
    name: "weave-gitops"
