---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  namespace: "victoria-metrics"
  name: "victoria-metrics"
spec:
  provider:
    aws:
      service: SecretsManager
      region: "us-west-2"
      auth:
        jwt:
          serviceAccountRef:
            name: "victoria-metrics-secret-store"
