---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  namespace: "argocd"
  name: "argocd-apps"
spec:
  interval: 15m
  timeout: 10m
  releaseName: "argocd-apps"
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        namespace: "argocd"
        name: "argocd"
      chart: argocd-apps
      version: "2.0.5"
  install:
    remediation:
      retries: 10
  upgrade:
    remediation:
      retries: 10
  valuesFrom:
  - kind: ConfigMap
    name: "argocd-apps-helm-values"
    valuesKey: values.yaml
