---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- polaris-namespace.yaml
- polaris-helm-release.yaml
- polaris-helm-repository.yaml
- polaris-helm-values.yaml
- polaris-http-routes.yaml
