---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  namespace: "kubenuts"
  name: "atlantis-secrets"
spec:
  dependsOn:
  - namespace: "kubenuts"
    name: "kubenuts-secret-store"
  interval: 10m
  prune: true
  sourceRef:
    kind: GitRepository
    namespace: flux-system
    name: flux-system
  path: "/manifests/atlantis/atlantis-secrets"
  targetNamespace: "kubenuts"
  healthChecks:
  - apiVersion: external-secrets.io/v1
    kind: ExternalSecret
    namespace: "kubenuts"
    name: "atlantis-gitconfig"
  - apiVersion: external-secrets.io/v1
    kind: ExternalSecret
    namespace: "kubenuts"
    name: "atlantis-github"
