---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- atlantis-helm-release.yaml
- atlantis-helm-repository.yaml
- atlantis-helm-values.yaml
- atlantis-webhook-gateway.yaml
- atlantis-webhook-route.yaml
