---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  namespace: "linkerd"
  name: "linkerd-certificates"
spec:
  dependsOn:
  - namespace: cert-manager
    name: cert-manager-helm-release
  - namespace: "linkerd"
    name: "linkerd-secret-store"
  interval: 10m
  prune: true
  sourceRef:
    kind: GitRepository
    namespace: flux-system
    name: flux-system
  path: "/manifests/linkerd/linkerd-certificates"
  targetNamespace: "linkerd"
  healthChecks:
  - apiVersion: external-secrets.io/v1
    kind: ExternalSecret
    namespace: "linkerd"
    name: "linkerd-root-cert"
  - apiVersion: v1
    kind: Secret
    namespace: "linkerd"
    name: "linkerd-root-cert"
  - apiVersion: cert-manager.io/v1
    kind: Issuer
    namespace: "linkerd"
    name: "linkerd-root-issuer"
  - apiVersion: cert-manager.io/v1
    kind: Certificate
    namespace: "linkerd"
    name: "linkerd-identity-issuer"
  - apiVersion: v1
    kind: Secret
    namespace: "linkerd"
    name: "linkerd-identity-issuer"
