---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  namespace: "linkerd"
  name: "linkerd-secret-store"
spec:
  dependsOn:
  - namespace: kubenuts
    name: external-secrets-helm-release
  interval: 10m
  prune: true
  sourceRef:
    kind: GitRepository
    namespace: flux-system
    name: flux-system
  path: "/manifests/linkerd/linkerd-secret-store"
  targetNamespace: "linkerd"
  healthChecks:
  - apiVersion: v1
    kind: ServiceAccount
    namespace: "linkerd"
    name: "linkerd-secret-store"
  - apiVersion: external-secrets.io/v1
    kind: SecretStore
    namespace: "linkerd"
    name: "linkerd"
