---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  namespace: "linkerd"
  name: "linkerd-crds-helm-release"
spec:
  interval: 10m
  prune: true
  sourceRef:
    kind: GitRepository
    namespace: flux-system
    name: flux-system
  path: "/manifests/linkerd/linkerd-crds-helm-release"
  targetNamespace: "linkerd"
  healthChecks:
  - apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    namespace: "linkerd"
    name: "linkerd-crds"
