---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  namespace: "linkerd"
  name: "linkerd-control-plane-helm-values"
spec:
  interval: 10m
  prune: true
  sourceRef:
    kind: GitRepository
    namespace: flux-system
    name: flux-system
  path: "/manifests/linkerd/linkerd-control-plane-helm-values"
  targetNamespace: "linkerd"
  healthChecks:
  - apiVersion: v1
    kind: ConfigMap
    namespace: "linkerd"
    name: "linkerd-control-plane-helm-values"
