---
clusterDomain: cluster.local
controllerReplicas: 1
enablePodAntiAffinity: true
enablePodDisruptionBudget: true
highAvailability: false
webhookFailurePolicy: Fail
deploymentStrategy:
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 25%
identity:
  issuer:
    scheme: kubernetes.io/tls
    issuanceLifetime: 24h0m0s
proxyInit:
  runAsRoot: true
  skipSubnets: "127.0.0.0/8"
podMonitor:
  enabled: false
policyValidator:
  externalSecret: true
profileValidator:
  externalSecret: true
proxyInjector:
  externalSecret: true
proxy:
  resources:    
    cpu:
      request: "50m"
policyController:
  resources:    
    cpu:
      request: "50m"
destinationResources:  
  cpu:
    request: "50m"
spValidatorResources:  
  cpu:
    request: "50m"
identityResources:  
  cpu:
    request: "50m"
proxyInjectorResources:  
  cpu:
    request: "50m"
