---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  namespace: "linkerd"
  name: "linkerd-license"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: "linkerd"
  target:
    name: "linkerd-license"
    creationPolicy: Owner
  data:
  - secretKey: license
    remoteRef:
      key: "pg02/linkerd/license"
