---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  namespace: "kubenuts"
  name: "atlantis-gitconfig"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: "kubenuts"
  target:
    name: "atlantis-gitconfig"
    creationPolicy: Owner
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        gitconfig: |
          [credential]
            helper = store
          [url "https://buvms:{{ .githubToken }}@github.com/"]
            insteadOf = ssh://git@github.com/
          [url "https://buvms:{{ .githubToken }}@github.com/"]
            insteadOf = git@github.com:
  data:
  - secretKey: githubToken
    remoteRef:
      key: "pg02/kubenuts/atlantis"
      property: github-token
