---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  namespace: "kubenuts"
  name: "atlantis-github"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: "kubenuts"
  target:
    name: "atlantis-github"
    creationPolicy: Owner
  data:
  - secretKey: ATLANTIS_GH_TOKEN
    remoteRef:
      key: "pg02/kubenuts/atlantis"
      property: github-token
  - secretKey: ATLANTIS_GH_WEBHOOK_SECRET
    remoteRef:
      key: "pg02/kubenuts/atlantis"
      property: github-webhook-secret
