---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- grafana-dashboards.yaml
- grafana-helm-release.yaml
- grafana-helm-repository.yaml
- grafana-helm-values.yaml
- grafana-secrets.yaml
