---
crds:
  enabled: false
  plain: false
env:
- name: VM_GATEWAY_API_ENABLED
  value: "true"
logLevel: error
operator:
  disable_prometheus_converter: false
  enable_converter_ownership: true
  prometheus_converter_add_argocd_ignore_annotations: true
replicaCount: 1
serviceMonitor:
  enabled: true
  relabelings:
  - replacement: vmoperator
    targetLabel: job
