---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  namespace: "linkerd"
  name: "linkerd-sp-validator"
spec:
  secretName: "linkerd-sp-validator-k8s-tls"
  duration: 1440h
  renewBefore: 240h
  issuerRef:
    kind: Issuer
    name: "linkerd-webhook-issuer"
  commonName: "linkerd-sp-validator.linkerd.svc"
  dnsNames:
  - "linkerd-sp-validator.linkerd.svc"
  privateKey:
    algorithm: ECDSA
  isCA: false
  usages:
  - server auth
