{
 "title": "OpenCost Overview",
 "description": "A dashboard that monitors OpenCost and focuses on giving a overview for OpenCost. The dashboards were generated using opencost-mixin. https://github.com/adinhodovic/opencost-mixin. Open issues and create feature requests in the repository.",
 "tags": [
  "opencost",
  "opencost-mixin"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(opencost_build_info{}, cluster)"
   },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(opencost_build_info{cluster=\"$cluster\"}, job)"
   }
  ]
 },
 "panels": [
  { "title": "Cluster Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Hourly Cost",
   "type": "stat",
   "description": "Shows the total hourly cost across the cluster.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum(\n  node_total_hourly_cost{\n    cluster=\"$cluster\"\n  }\n) \n+\nsum(\n  sum(\n    kube_persistentvolume_capacity_bytes{\n      cluster=\"$cluster\"\n    } / (1024 * 1024 * 1024)\n  ) by (persistentvolume)\n  * on(persistentvolume) group_left()\n  sum(\n    pv_hourly_cost{\n      cluster=\"$cluster\"\n    }\n  ) by (persistentvolume)\n) \n"
    }
   ]
  },
  {
   "title": "Daily Cost",
   "type": "stat",
   "description": "Shows the total daily cost across the cluster.",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum(\n  node_total_hourly_cost{\n    cluster=\"$cluster\"\n  }\n) * 24\n+\nsum(\n  sum(\n    kube_persistentvolume_capacity_bytes{\n      cluster=\"$cluster\"\n    } / (1024 * 1024 * 1024)\n  ) by (persistentvolume)\n  * on(persistentvolume) group_left()\n  sum(\n    pv_hourly_cost{\n      cluster=\"$cluster\"\n    }\n  ) by (persistentvolume)\n) * 24\n"
    }
   ]
  },
  {
   "title": "Monthly Cost",
   "type": "stat",
   "description": "Shows the total monthly cost across the cluster.",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum(\n  node_total_hourly_cost{\n    cluster=\"$cluster\"\n  }\n) * 730\n+\nsum(\n  sum(\n    kube_persistentvolume_capacity_bytes{\n      cluster=\"$cluster\"\n    } / (1024 * 1024 * 1024)\n  ) by (persistentvolume)\n  * on(persistentvolume) group_left()\n  sum(\n    pv_hourly_cost{\n      cluster=\"$cluster\"\n    }\n  ) by (persistentvolume)\n) * 730\n"
    }
   ]
  },
  {
   "title": "Monthly CPU Cost",
   "type": "stat",
   "description": "Shows the total monthly CPU cost across the cluster.",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum(\n  sum(\n    kube_node_status_capacity{\n      cluster=\"$cluster\",\n      resource=\"cpu\",\n      unit=\"core\"\n    }\n  ) by (node)\n  * on(node) group_left()\n    sum(\n      node_cpu_hourly_cost{\n        cluster=\"$cluster\"\n      }\n    ) by (node)\n  * 730\n)\n"
    }
   ]
  },
  {
   "title": "Monthly Ram Cost",
   "type": "stat",
   "description": "Shows the total monthly RAM cost across the cluster.",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum(\n  sum(\n    kube_node_status_capacity{\n      cluster=\"$cluster\",\n      resource=\"memory\",\n      unit=\"byte\"\n    }\n  ) by (node)\n  / (1024 * 1024 * 1024)\n  * on(node) group_left()\n    sum(\n      node_ram_hourly_cost{\n        cluster=\"$cluster\"\n      }\n    ) by (node)\n  * 730\n)\n"
    }
   ]
  },
  {
   "title": "Monthly PV Cost",
   "type": "stat",
   "description": "Shows the total monthly Persistent Volume cost across the cluster.",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum(\n  sum(\n    kube_persistentvolume_capacity_bytes{\n      cluster=\"$cluster\"\n    } / (1024 * 1024 * 1024)\n  ) by (persistentvolume)\n  * on(persistentvolume) group_left()\n    sum(\n      pv_hourly_cost{\n        cluster=\"$cluster\"\n      }\n    ) by (persistentvolume)\n) * 730\n"
    }
   ]
  },
  {
   "title": "Hourly Cost",
   "type": "timeseries",
   "description": "Shows the hourly cost across the cluster.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum(\n  node_total_hourly_cost{\n    cluster=\"$cluster\"\n  }\n) \n+\nsum(\n  sum(\n    kube_persistentvolume_capacity_bytes{\n      cluster=\"$cluster\"\n    } / (1024 * 1024 * 1024)\n  ) by (persistentvolume)\n  * on(persistentvolume) group_left()\n  sum(\n    pv_hourly_cost{\n      cluster=\"$cluster\"\n    }\n  ) by (persistentvolume)\n) \n",
     "legendFormat": "Hourly Cost"
    }
   ]
  },
  {
   "title": "Daily Cost",
   "type": "timeseries",
   "description": "Shows the daily cost across the cluster.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum(\n  node_total_hourly_cost{\n    cluster=\"$cluster\"\n  }\n) * 24\n+\nsum(\n  sum(\n    kube_persistentvolume_capacity_bytes{\n      cluster=\"$cluster\"\n    } / (1024 * 1024 * 1024)\n  ) by (persistentvolume)\n  * on(persistentvolume) group_left()\n  sum(\n    pv_hourly_cost{\n      cluster=\"$cluster\"\n    }\n  ) by (persistentvolume)\n) * 24\n",
     "legendFormat": "Daily Cost"
    }
   ]
  },
  {
   "title": "Monthly Cost",
   "type": "timeseries",
   "description": "Shows the monthly cost across the cluster.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum(\n  node_total_hourly_cost{\n    cluster=\"$cluster\"\n  }\n) * 730\n+\nsum(\n  sum(\n    kube_persistentvolume_capacity_bytes{\n      cluster=\"$cluster\"\n    } / (1024 * 1024 * 1024)\n  ) by (persistentvolume)\n  * on(persistentvolume) group_left()\n  sum(\n    pv_hourly_cost{\n      cluster=\"$cluster\"\n    }\n  ) by (persistentvolume)\n) * 730\n",
     "legendFormat": "Monthly Cost"
    }
   ]
  },
  {
   "title": "Cost by Resource",
   "type": "piechart",
   "description": "Shows the cost by resource across the cluster.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum(\n  sum(\n    kube_node_status_capacity{\n      cluster=\"$cluster\",\n      resource=\"cpu\",\n      unit=\"core\"\n    }\n  ) by (node)\n  * on(node) group_left()\n    sum(\n      node_cpu_hourly_cost{\n        cluster=\"$cluster\"\n      }\n    ) by (node)\n  * 730\n)\n",
     "legendFormat": "CPU"
    },
    {
     "expr": "sum(\n  sum(\n    kube_node_status_capacity{\n      cluster=\"$cluster\",\n      resource=\"memory\",\n      unit=\"byte\"\n    }\n  ) by (node)\n  / (1024 * 1024 * 1024)\n  * on(node) group_left()\n    sum(\n      node_ram_hourly_cost{\n        cluster=\"$cluster\"\n      }\n    ) by (node)\n  * 730\n)\n",
     "legendFormat": "RAM"
    },
    {
     "expr": "sum(\n  sum(\n    kube_persistentvolume_capacity_bytes{\n      cluster=\"$cluster\"\n    } / (1024 * 1024 * 1024)\n  ) by (persistentvolume)\n  * on(persistentvolume) group_left()\n    sum(\n      pv_hourly_cost{\n        cluster=\"$cluster\"\n      }\n    ) by (persistentvolume)\n) * 730\n",
     "legendFormat": "PV"
    }
   ]
  },
  {
   "title": "Cost by Namespace",
   "type": "piechart",
   "description": "Shows the cost by namespace across the cluster.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "topk(10,\n  sum(\n    sum(\n      container_memory_allocation_bytes{\n        cluster=\"$cluster\"}\n    ) by (namespace, instance)\n    * on(instance) group_left()\n      (\n        node_ram_hourly_cost{\n          cluster=\"$cluster\"} / (1024 * 1024 * 1024) * 730\n      )\n    +\n    sum(\n      container_cpu_allocation{\n        cluster=\"$cluster\"}\n    ) by (namespace, instance)\n    * on(instance) group_left()\n      (\n        node_cpu_hourly_cost{\n          cluster=\"$cluster\"} * 730\n      )\n  ) by (namespace)\n)\n",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Cost by Instance Type",
   "type": "piechart",
   "description": "Shows the cost by instance type across the cluster.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "topk(10,\n  sum(\n    node_total_hourly_cost{\n      cluster=\"$cluster\"\n    }\n  ) by (instance_type) * 730\n)\n",
     "legendFormat": "{{ instance_type }}"
    }
   ]
  },
  {
   "title": "Total Cost Variance",
   "type": "timeseries",
   "description": "Shows the total cost variance across the cluster.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\n  avg_over_time(\n    sum(\n      node_total_hourly_cost{\n        cluster=\"$cluster\"\n      }\n    ) [1d:1h]\n  )\n  -\n  avg_over_time(\n    sum(\n      node_total_hourly_cost{\n        cluster=\"$cluster\"\n      }\n    ) [7d:1h]\n  )\n)\n/\navg_over_time(\n  sum(\n    node_total_hourly_cost{\n      cluster=\"$cluster\"\n    }\n  ) [7d:1h]\n)\n",
     "legendFormat": "Current hourly cost vs. 7-day average"
    },
    {
     "expr": "(\n  avg_over_time(\n    sum(\n      node_total_hourly_cost{\n        cluster=\"$cluster\"\n      }\n    ) [1d:1h]\n  )\n  -\n  avg_over_time(\n    sum(\n      node_total_hourly_cost{\n        cluster=\"$cluster\"\n      }\n    ) [30d:1h]\n  )\n)\n/\navg_over_time(\n  sum(\n    node_total_hourly_cost{\n      cluster=\"$cluster\"\n    }\n  ) [30d:1h]\n)\n",
     "legendFormat": "Current hourly cost vs. 30-day average"
    }
   ]
  },
  {
   "title": "Resource Cost Variance",
   "type": "timeseries",
   "description": "Shows the resource cost variance across the cluster.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\n  avg_over_time(\n    sum(\n  sum(\n    kube_node_status_capacity{\n      cluster=\"$cluster\",\n      resource=\"cpu\",\n      unit=\"core\"\n    }\n  ) by (node)\n  * on(node) group_left()\n    sum(\n      node_cpu_hourly_cost{\n        cluster=\"$cluster\"\n      }\n    ) by (node)\n  * 730\n)\n [1d:1h]\n  )\n  -\n  avg_over_time(\n    sum(\n  sum(\n    kube_node_status_capacity{\n      cluster=\"$cluster\",\n      resource=\"cpu\",\n      unit=\"core\"\n    }\n  ) by (node)\n  * on(node) group_left()\n    sum(\n      node_cpu_hourly_cost{\n        cluster=\"$cluster\"\n      }\n    ) by (node)\n  * 730\n)\n [30d:1h]\n  )\n)\n/\navg_over_time(\n  sum(\n  sum(\n    kube_node_status_capacity{\n      cluster=\"$cluster\",\n      resource=\"cpu\",\n      unit=\"core\"\n    }\n  ) by (node)\n  * on(node) group_left()\n    sum(\n      node_cpu_hourly_cost{\n        cluster=\"$cluster\"\n      }\n    ) by (node)\n  * 730\n)\n [30d:1h]\n)\n",
     "legendFormat": "CPU Cost vs. 30-day average"
    },
    {
     "expr": "(\n  avg_over_time(\n    sum(\n  sum(\n    kube_node_status_capacity{\n      cluster=\"$cluster\",\n      resource=\"memory\",\n      unit=\"byte\"\n    }\n  ) by (node)\n  / (1024 * 1024 * 1024)\n  * on(node) group_left()\n    sum(\n      node_ram_hourly_cost{\n        cluster=\"$cluster\"\n      }\n    ) by (node)\n  * 730\n)\n [1d:1h]\n  )\n  -\n  avg_over_time(\n    sum(\n  sum(\n    kube_node_status_capacity{\n      cluster=\"$cluster\",\n      resource=\"memory\",\n      unit=\"byte\"\n    }\n  ) by (node)\n  / (1024 * 1024 * 1024)\n  * on(node) group_left()\n    sum(\n      node_ram_hourly_cost{\n        cluster=\"$cluster\"\n      }\n    ) by (node)\n  * 730\n)\n [30d:1h]\n  )\n)\n/\navg_over_time(\n  sum(\n  sum(\n    kube_node_status_capacity{\n      cluster=\"$cluster\",\n      resource=\"memory\",\n      unit=\"byte\"\n    }\n  ) by (node)\n  / (1024 * 1024 * 1024)\n  * on(node) group_left()\n    sum(\n      node_ram_hourly_cost{\n        cluster=\"$cluster\"\n      }\n    ) by (node)\n  * 730\n)\n [30d:1h]\n)\n",
     "legendFormat": "RAM Cost vs. 30-day average"
    },
    {
     "expr": "(\n  avg_over_time(\n    (sum(\n  sum(\n    kube_persistentvolume_capacity_bytes{\n      cluster=\"$cluster\"\n    } / (1024 * 1024 * 1024)\n  ) by (persistentvolume)\n  * on(persistentvolume) group_left()\n    sum(\n      pv_hourly_cost{\n        cluster=\"$cluster\"\n      }\n    ) by (persistentvolume)\n) * 730\n) [1d:1h]\n  )\n  -\n  avg_over_time(\n    (sum(\n  sum(\n    kube_persistentvolume_capacity_bytes{\n      cluster=\"$cluster\"\n    } / (1024 * 1024 * 1024)\n  ) by (persistentvolume)\n  * on(persistentvolume) group_left()\n    sum(\n      pv_hourly_cost{\n        cluster=\"$cluster\"\n      }\n    ) by (persistentvolume)\n) * 730\n) [30d:1h]\n  )\n)\n/\navg_over_time(\n  (sum(\n  sum(\n    kube_persistentvolume_capacity_bytes{\n      cluster=\"$cluster\"\n    } / (1024 * 1024 * 1024)\n  ) by (persistentvolume)\n  * on(persistentvolume) group_left()\n    sum(\n      pv_hourly_cost{\n        cluster=\"$cluster\"\n      }\n    ) by (persistentvolume)\n) * 730\n) [30d:1h]\n)\n",
     "legendFormat": "PV Cost vs. 30-day average"
    }
   ]
  },
  { "title": "Cloud Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Nodes Monthly Cost",
   "type": "table",
   "description": "Shows the monthly cost by node across the cluster.",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum(\n  kube_node_status_capacity{\n    cluster=\"$cluster\",\n    resource=\"cpu\",\n    unit=\"core\"\n  }\n) by (node)\n* on(node) group_left(cluster, instance_type, arch)\n  sum(\n    node_cpu_hourly_cost{\n      cluster=\"$cluster\",\n    }\n  ) by (node, instance_type, arch)\n* 730\n"
    },
    {
     "expr": "sum(\n  kube_node_status_capacity{\n    cluster=\"$cluster\",\n    resource=\"memory\",\n    unit=\"byte\"\n  }\n) by (node)\n/ (1024 * 1024 * 1024)\n* on(node) group_left(cluster, instance_type, arch)\n  sum(\n    node_ram_hourly_cost{\n      cluster=\"$cluster\"\n    }\n  ) by (node, instance_type, arch)\n* 730\n"
    },
    {
     "expr": "sum(\n  node_total_hourly_cost{\n    cluster=\"$cluster\"\n  }\n) by (node, instance_type, arch)\n* 730\n"
    }
   ]
  },
  {
   "title": "Persistent Volumes Monthly Cost",
   "type": "table",
   "description": "Shows the monthly cost by persistent volume across the cluster.",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "sum(\n  kube_persistentvolume_capacity_bytes{\n    cluster=\"$cluster\"\n  }\n  / 1024 / 1024 / 1024\n) by (persistentvolume)\n"
    },
    {
     "expr": "sum(\n  kube_persistentvolume_capacity_bytes{\n    cluster=\"$cluster\"\n  }\n  / 1024 / 1024 / 1024\n) by (persistentvolume)\n*\nsum(\n  pv_hourly_cost{\n    cluster=\"$cluster\"\n  }\n  * 730\n) by (persistentvolume)\n"
    }
   ]
  },
  { "title": "Namespace Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Namespace Monthly Cost",
   "type": "table",
   "description": "Shows the monthly cost by namespace across the cluster.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "topk(10,\n  sum(\n    sum(\n      container_memory_allocation_bytes{\n        cluster=\"$cluster\"}\n    ) by (namespace, instance)\n    * on(instance) group_left()\n      (\n        node_ram_hourly_cost{\n          cluster=\"$cluster\"} / (1024 * 1024 * 1024) * 730\n      )\n    +\n    sum(\n      container_cpu_allocation{\n        cluster=\"$cluster\"}\n    ) by (namespace, instance)\n    * on(instance) group_left()\n      (\n        node_cpu_hourly_cost{\n          cluster=\"$cluster\"} * 730\n      )\n  ) by (namespace)\n)\n"
    },
    {
     "expr": "topk(10,\n  sum(\n    sum(\n      container_memory_allocation_bytes{\n        cluster=\"$cluster\"}\n    ) by (namespace, instance)\n    * on(instance) group_left()\n      (\n        node_ram_hourly_cost{\n          cluster=\"$cluster\"} / (1024 * 1024 * 1024) * 730\n      )\n    +\n    sum(\n      container_cpu_allocation{\n        cluster=\"$cluster\"}\n    ) by (namespace, instance)\n    * on(instance) group_left()\n      (\n        node_cpu_hourly_cost{\n          cluster=\"$cluster\"} * 730\n      )\n  ) by (namespace)\n)\n\n/\ntopk(10,\n  sum(\n    sum(\n      container_memory_allocation_bytes{\n        cluster=\"$cluster\"} offset 7d\n    ) by (namespace, instance)\n    * on(instance) group_left()\n      (\n        node_ram_hourly_cost{\n          cluster=\"$cluster\"} offset 7d / (1024 * 1024 * 1024) * 730\n      )\n    +\n    sum(\n      container_cpu_allocation{\n        cluster=\"$cluster\"} offset 7d\n    ) by (namespace, instance)\n    * on(instance) group_left()\n      (\n        node_cpu_hourly_cost{\n          cluster=\"$cluster\"} offset 7d * 730\n      )\n  ) by (namespace)\n)\n\n* 100\n- 100\n"
    },
    {
     "expr": "topk(10,\n  sum(\n    sum(\n      container_memory_allocation_bytes{\n        cluster=\"$cluster\"}\n    ) by (namespace, instance)\n    * on(instance) group_left()\n      (\n        node_ram_hourly_cost{\n          cluster=\"$cluster\"} / (1024 * 1024 * 1024) * 730\n      )\n    +\n    sum(\n      container_cpu_allocation{\n        cluster=\"$cluster\"}\n    ) by (namespace, instance)\n    * on(instance) group_left()\n      (\n        node_cpu_hourly_cost{\n          cluster=\"$cluster\"} * 730\n      )\n  ) by (namespace)\n)\n\n/\ntopk(10,\n  sum(\n    sum(\n      container_memory_allocation_bytes{\n        cluster=\"$cluster\"} offset 7d\n    ) by (namespace, instance)\n    * on(instance) group_left()\n      (\n        node_ram_hourly_cost{\n          cluster=\"$cluster\"} offset 7d / (1024 * 1024 * 1024) * 730\n      )\n    +\n    sum(\n      container_cpu_allocation{\n        cluster=\"$cluster\"} offset 7d\n    ) by (namespace, instance)\n    * on(instance) group_left()\n      (\n        node_cpu_hourly_cost{\n          cluster=\"$cluster\"} offset 7d * 730\n      )\n  ) by (namespace)\n)\n\n* 100\n- 100\n"
    }
   ]
  }
 ]
}
{
 "title": "OpenCost Namespace",
 "description": "A dashboard that monitors OpenCost and focuses on namespace costs. The dashboards were generated using opencost-mixin. https://github.com/adinhodovic/opencost-mixin. Open issues and create feature requests in the repository.",
 "tags": [
  "opencost",
  "opencost-mixin"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(opencost_build_info{}, cluster)"
   },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(opencost_build_info{cluster=\"$cluster\"}, job)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_namespace_labels{cluster=\"$cluster\"}, namespace)"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Hourly Cost",
   "type": "stat",
   "description": "Shows the total daily cost across the cluster.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum(\n  sum(\n    container_memory_allocation_bytes{\n      cluster=\"$cluster\",\nnamespace=\"$namespace\"\n\n    }\n  )\n  by (namespace, instance)\n  * on(instance) group_left()\n  (\n    avg(\n      node_ram_hourly_cost{\n        cluster=\"$cluster\"\n      }\n    ) by (instance) / (1024 * 1024 * 1024) * 1\n  )\n)\n\n+\nsum(\n  sum(\n    container_cpu_allocation{\n      cluster=\"$cluster\",\nnamespace=\"$namespace\"\n\n    }\n  )\n  by (namespace, instance)\n  * on(instance) group_left()\n  (\n    avg(\n      node_cpu_hourly_cost{\n        cluster=\"$cluster\"\n      }\n    ) by (instance) * 1\n  )\n)\n\n+\nsum(\n  sum(\n    kube_persistentvolume_capacity_bytes{\n      cluster=\"$cluster\"\n    }\n    / (1024 * 1024 * 1024)\n  ) by (persistentvolume)\n  *\n  sum(\n    pv_hourly_cost{\n      cluster=\"$cluster\"\n    }\n  ) by (persistentvolume)\n  * on(persistentvolume) group_left(cluster, namespace) (\n    label_replace(\n      kube_persistentvolumeclaim_info{\n        cluster=\"$cluster\",\nnamespace=\"$namespace\"\n\n      },\n      \"persistentvolume\", \"$1\",\n      \"volumename\", \"(.*)\"\n    )\n  ) or vector(0)\n) * 1\n\n"
    }
   ]
  },
  {
   "title": "Daily Cost",
   "type": "stat",
   "description": "Shows the total daily cost across the cluster.",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum(\n  sum(\n    container_memory_allocation_bytes{\n      cluster=\"$cluster\",\nnamespace=\"$namespace\"\n\n    }\n  )\n  by (namespace, instance)\n  * on(instance) group_left()\n  (\n    avg(\n      node_ram_hourly_cost{\n        cluster=\"$cluster\"\n      }\n    ) by (instance) / (1024 * 1024 * 1024) * 24\n  )\n)\n\n+\nsum(\n  sum(\n    container_cpu_allocation{\n      cluster=\"$cluster\",\nnamespace=\"$namespace\"\n\n    }\n  )\n  by (namespace, instance)\n  * on(instance) group_left()\n  (\n    avg(\n      node_cpu_hourly_cost{\n        cluster=\"$cluster\"\n      }\n    ) by (instance) * 24\n  )\n)\n\n+\nsum(\n  sum(\n    kube_persistentvolume_capacity_bytes{\n      cluster=\"$cluster\"\n    }\n    / (1024 * 1024 * 1024)\n  ) by (persistentvolume)\n  *\n  sum(\n    pv_hourly_cost{\n      cluster=\"$cluster\"\n    }\n  ) by (persistentvolume)\n  * on(persistentvolume) group_left(cluster, namespace) (\n    label_replace(\n      kube_persistentvolumeclaim_info{\n        cluster=\"$cluster\",\nnamespace=\"$namespace\"\n\n      },\n      \"persistentvolume\", \"$1\",\n      \"volumename\", \"(.*)\"\n    )\n  ) or vector(0)\n) * 24\n\n"
    }
   ]
  },
  {
   "title": "Monthly Cost",
   "type": "stat",
   "description": "Shows the total monthly cost across the cluster.",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum(\n  sum(\n    container_memory_allocation_bytes{\n      cluster=\"$cluster\",\nnamespace=\"$namespace\"\n\n    }\n  )\n  by (namespace, instance)\n  * on(instance) group_left()\n  (\n    avg(\n      node_ram_hourly_cost{\n        cluster=\"$cluster\"\n      }\n    ) by (instance) / (1024 * 1024 * 1024) * 730\n  )\n)\n\n+\nsum(\n  sum(\n    container_cpu_allocation{\n      cluster=\"$cluster\",\nnamespace=\"$namespace\"\n\n    }\n  )\n  by (namespace, instance)\n  * on(instance) group_left()\n  (\n    avg(\n      node_cpu_hourly_cost{\n        cluster=\"$cluster\"\n      }\n    ) by (instance) * 730\n  )\n)\n\n+\nsum(\n  sum(\n    kube_persistentvolume_capacity_bytes{\n      cluster=\"$cluster\"\n    }\n    / (1024 * 1024 * 1024)\n  ) by (persistentvolume)\n  *\n  sum(\n    pv_hourly_cost{\n      cluster=\"$cluster\"\n    }\n  ) by (persistentvolume)\n  * on(persistentvolume) group_left(cluster, namespace) (\n    label_replace(\n      kube_persistentvolumeclaim_info{\n        cluster=\"$cluster\",\nnamespace=\"$namespace\"\n\n      },\n      \"persistentvolume\", \"$1\",\n      \"volumename\", \"(.*)\"\n    )\n  ) or vector(0)\n) * 730\n\n"
    }
   ]
  },
  {
   "title": "Monthly CPU Cost",
   "type": "stat",
   "description": "Shows the total monthly CPU cost across the cluster.",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum(\n  sum(\n    container_cpu_allocation{\n      cluster=\"$cluster\",\nnamespace=\"$namespace\"\n\n    }\n  )\n  by (namespace, instance)\n  * on(instance) group_left()\n  (\n    avg(\n      node_cpu_hourly_cost{\n        cluster=\"$cluster\"\n      }\n    ) by (instance) * 730\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Monthly Ram Cost",
   "type": "stat",
   "description": "Shows the total monthly RAM cost across the cluster.",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum(\n  sum(\n    container_memory_allocation_bytes{\n      cluster=\"$cluster\",\nnamespace=\"$namespace\"\n\n    }\n  )\n  by (namespace, instance)\n  * on(instance) group_left()\n  (\n    avg(\n      node_ram_hourly_cost{\n        cluster=\"$cluster\"\n      }\n    ) by (instance) / (1024 * 1024 * 1024) * 730\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Monthly PV Cost",
   "type": "stat",
   "description": "Shows the total monthly Persistent Volume cost across the cluster.",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum(\n  sum(\n    kube_persistentvolume_capacity_bytes{\n      cluster=\"$cluster\"\n    }\n    / (1024 * 1024 * 1024)\n  ) by (persistentvolume)\n  *\n  sum(\n    pv_hourly_cost{\n      cluster=\"$cluster\"\n    }\n  ) by (persistentvolume)\n  * on(persistentvolume) group_left(cluster, namespace) (\n    label_replace(\n      kube_persistentvolumeclaim_info{\n        cluster=\"$cluster\",\nnamespace=\"$namespace\"\n\n      },\n      \"persistentvolume\", \"$1\",\n      \"volumename\", \"(.*)\"\n    )\n  )\n) * 730\n"
    }
   ]
  },
  {
   "title": "Daily Cost",
   "type": "timeseries",
   "description": "Shows the total daily cost across the cluster over time.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum(\n  sum(\n    container_memory_allocation_bytes{\n      cluster=\"$cluster\",\nnamespace=\"$namespace\"\n\n    }\n  )\n  by (namespace, instance)\n  * on(instance) group_left()\n  (\n    avg(\n      node_ram_hourly_cost{\n        cluster=\"$cluster\"\n      }\n    ) by (instance) / (1024 * 1024 * 1024) * 24\n  )\n)\n\n+\nsum(\n  sum(\n    container_cpu_allocation{\n      cluster=\"$cluster\",\nnamespace=\"$namespace\"\n\n    }\n  )\n  by (namespace, instance)\n  * on(instance) group_left()\n  (\n    avg(\n      node_cpu_hourly_cost{\n        cluster=\"$cluster\"\n      }\n    ) by (instance) * 24\n  )\n)\n\n+\nsum(\n  sum(\n    kube_persistentvolume_capacity_bytes{\n      cluster=\"$cluster\"\n    }\n    / (1024 * 1024 * 1024)\n  ) by (persistentvolume)\n  *\n  sum(\n    pv_hourly_cost{\n      cluster=\"$cluster\"\n    }\n  ) by (persistentvolume)\n  * on(persistentvolume) group_left(cluster, namespace) (\n    label_replace(\n      kube_persistentvolumeclaim_info{\n        cluster=\"$cluster\",\nnamespace=\"$namespace\"\n\n      },\n      \"persistentvolume\", \"$1\",\n      \"volumename\", \"(.*)\"\n    )\n  ) or vector(0)\n) * 24\n\n",
     "legendFormat": "Daily Cost"
    }
   ]
  },
  {
   "title": "Monthly Cost",
   "type": "timeseries",
   "description": "Shows the total monthly cost across the cluster over time.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum(\n  sum(\n    container_memory_allocation_bytes{\n      cluster=\"$cluster\",\nnamespace=\"$namespace\"\n\n    }\n  )\n  by (namespace, instance)\n  * on(instance) group_left()\n  (\n    avg(\n      node_ram_hourly_cost{\n        cluster=\"$cluster\"\n      }\n    ) by (instance) / (1024 * 1024 * 1024) * 730\n  )\n)\n\n+\nsum(\n  sum(\n    container_cpu_allocation{\n      cluster=\"$cluster\",\nnamespace=\"$namespace\"\n\n    }\n  )\n  by (namespace, instance)\n  * on(instance) group_left()\n  (\n    avg(\n      node_cpu_hourly_cost{\n        cluster=\"$cluster\"\n      }\n    ) by (instance) * 730\n  )\n)\n\n+\nsum(\n  sum(\n    kube_persistentvolume_capacity_bytes{\n      cluster=\"$cluster\"\n    }\n    / (1024 * 1024 * 1024)\n  ) by (persistentvolume)\n  *\n  sum(\n    pv_hourly_cost{\n      cluster=\"$cluster\"\n    }\n  ) by (persistentvolume)\n  * on(persistentvolume) group_left(cluster, namespace) (\n    label_replace(\n      kube_persistentvolumeclaim_info{\n        cluster=\"$cluster\",\nnamespace=\"$namespace\"\n\n      },\n      \"persistentvolume\", \"$1\",\n      \"volumename\", \"(.*)\"\n    )\n  ) or vector(0)\n) * 730\n\n",
     "legendFormat": "Monthly Cost"
    }
   ]
  },
  {
   "title": "Cost by Resource",
   "type": "piechart",
   "description": "Shows the cost by resource across the cluster.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum(\n  sum(\n    container_cpu_allocation{\n      cluster=\"$cluster\",\nnamespace=\"$namespace\"\n\n    }\n  )\n  by (namespace, instance)\n  * on(instance) group_left()\n  (\n    avg(\n      node_cpu_hourly_cost{\n        cluster=\"$cluster\"\n      }\n    ) by (instance) * 730\n  )\n)\n",
     "legendFormat": "CPU"
    },
    {
     "expr": "sum(\n  sum(\n    container_memory_allocation_bytes{\n      cluster=\"$cluster\",\nnamespace=\"$namespace\"\n\n    }\n  )\n  by (namespace, instance)\n  * on(instance) group_left()\n  (\n    avg(\n      node_ram_hourly_cost{\n        cluster=\"$cluster\"\n      }\n    ) by (instance) / (1024 * 1024 * 1024) * 730\n  )\n)\n",
     "legendFormat": "RAM"
    },
    {
     "expr": "sum(\n  sum(\n    kube_persistentvolume_capacity_bytes{\n      cluster=\"$cluster\"\n    }\n    / (1024 * 1024 * 1024)\n  ) by (persistentvolume)\n  *\n  sum(\n    pv_hourly_cost{\n      cluster=\"$cluster\"\n    }\n  ) by (persistentvolume)\n  * on(persistentvolume) group_left(cluster, namespace) (\n    label_replace(\n      kube_persistentvolumeclaim_info{\n        cluster=\"$cluster\",\nnamespace=\"$namespace\"\n\n      },\n      \"persistentvolume\", \"$1\",\n      \"volumename\", \"(.*)\"\n    )\n  )\n) * 730\n",
     "legendFormat": "PV"
    }
   ]
  },
  { "title": "Pod Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Pod Monthly Cost",
   "type": "table",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "topk(10,\n  sum(\n    (\n      sum(\n        container_memory_allocation_bytes{\n          cluster=\"$cluster\",\n          namespace=\"$namespace\"}\n      )\n      by (instance, pod)\n      * on(instance) group_left()\n      (\n        avg(\n          node_ram_hourly_cost{\n            cluster=\"$cluster\"}\n        ) by (instance) / (1024 * 1024 * 1024) * 730\n      )\n    )\n    +\n    (\n      sum(\n        container_cpu_allocation{\n          cluster=\"$cluster\",\n          namespace=\"$namespace\"}\n      )\n      by (instance, pod)\n      * on(instance) group_left()\n      (\n        avg(\n          node_cpu_hourly_cost{\n            cluster=\"$cluster\"}\n        ) by (instance) * 730)\n    )\n  ) by (pod)\n)\n"
    },
    {
     "expr": "topk(10,\n  sum(\n    (\n      sum(\n        container_memory_allocation_bytes{\n          cluster=\"$cluster\",\n          namespace=\"$namespace\"}\n      )\n      by (instance, pod)\n      * on(instance) group_left()\n      (\n        avg(\n          node_ram_hourly_cost{\n            cluster=\"$cluster\"}\n        ) by (instance) / (1024 * 1024 * 1024) * 730\n      )\n    )\n    +\n    (\n      sum(\n        container_cpu_allocation{\n          cluster=\"$cluster\",\n          namespace=\"$namespace\"}\n      )\n      by (instance, pod)\n      * on(instance) group_left()\n      (\n        avg(\n          node_cpu_hourly_cost{\n            cluster=\"$cluster\"}\n        ) by (instance) * 730)\n    )\n  ) by (pod)\n)\n\n/\ntopk(10,\n  sum(\n    (\n      sum(\n        container_memory_allocation_bytes{\n          cluster=\"$cluster\",\n          namespace=\"$namespace\"} offset 7d\n      )\n      by (instance, pod)\n      * on(instance) group_left()\n      (\n        avg(\n          node_ram_hourly_cost{\n            cluster=\"$cluster\"} offset 7d\n        ) by (instance) / (1024 * 1024 * 1024) * 730\n      )\n    )\n    +\n    (\n      sum(\n        container_cpu_allocation{\n          cluster=\"$cluster\",\n          namespace=\"$namespace\"} offset 7d\n      )\n      by (instance, pod)\n      * on(instance) group_left()\n      (\n        avg(\n          node_cpu_hourly_cost{\n            cluster=\"$cluster\"} offset 7d\n        ) by (instance) * 730)\n    )\n  ) by (pod)\n)\n\n* 100\n- 100\n"
    },
    {
     "expr": "topk(10,\n  sum(\n    (\n      sum(\n        container_memory_allocation_bytes{\n          cluster=\"$cluster\",\n          namespace=\"$namespace\"}\n      )\n      by (instance, pod)\n      * on(instance) group_left()\n      (\n        avg(\n          node_ram_hourly_cost{\n            cluster=\"$cluster\"}\n        ) by (instance) / (1024 * 1024 * 1024) * 730\n      )\n    )\n    +\n    (\n      sum(\n        container_cpu_allocation{\n          cluster=\"$cluster\",\n          namespace=\"$namespace\"}\n      )\n      by (instance, pod)\n      * on(instance) group_left()\n      (\n        avg(\n          node_cpu_hourly_cost{\n            cluster=\"$cluster\"}\n        ) by (instance) * 730)\n    )\n  ) by (pod)\n)\n\n/\ntopk(10,\n  sum(\n    (\n      sum(\n        container_memory_allocation_bytes{\n          cluster=\"$cluster\",\n          namespace=\"$namespace\"} offset 30d\n      )\n      by (instance, pod)\n      * on(instance) group_left()\n      (\n        avg(\n          node_ram_hourly_cost{\n            cluster=\"$cluster\"} offset 30d\n        ) by (instance) / (1024 * 1024 * 1024) * 730\n      )\n    )\n    +\n    (\n      sum(\n        container_cpu_allocation{\n          cluster=\"$cluster\",\n          namespace=\"$namespace\"} offset 30d\n      )\n      by (instance, pod)\n      * on(instance) group_left()\n      (\n        avg(\n          node_cpu_hourly_cost{\n            cluster=\"$cluster\"} offset 30d\n        ) by (instance) * 730)\n    )\n  ) by (pod)\n)\n\n* 100\n- 100\n"
    }
   ]
  },
  {
   "title": "Cost by Pod",
   "type": "piechart",
   "description": "Shows the cost by pod across the cluster.",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "topk(10,\n  sum(\n    (\n      sum(\n        container_memory_allocation_bytes{\n          cluster=\"$cluster\",\n          namespace=\"$namespace\"}\n      )\n      by (instance, pod)\n      * on(instance) group_left()\n      (\n        avg(\n          node_ram_hourly_cost{\n            cluster=\"$cluster\"}\n        ) by (instance) / (1024 * 1024 * 1024) * 730\n      )\n    )\n    +\n    (\n      sum(\n        container_cpu_allocation{\n          cluster=\"$cluster\",\n          namespace=\"$namespace\"}\n      )\n      by (instance, pod)\n      * on(instance) group_left()\n      (\n        avg(\n          node_cpu_hourly_cost{\n            cluster=\"$cluster\"}\n        ) by (instance) * 730)\n    )\n  ) by (pod)\n)\n",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  { "title": "Container Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Container Monthly Cost",
   "type": "table",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "topk(10,\n  sum(\n    (\n      sum(\n        container_memory_allocation_bytes{\n          cluster=\"$cluster\",\n          namespace=\"$namespace\"}\n      )\n      by (instance, container)\n      * on(instance) group_left()\n      (\n        avg(\n          node_ram_hourly_cost{\n            cluster=\"$cluster\"}\n        ) by (instance) / (1024 * 1024 * 1024) * 730\n      )\n    )\n    +\n    (\n      sum(\n        container_cpu_allocation{\n          cluster=\"$cluster\",\n          namespace=\"$namespace\"}\n      )\n      by (instance, container)\n      * on(instance) group_left()\n      (\n        avg(\n          node_cpu_hourly_cost{\n            cluster=\"$cluster\"}\n        ) by (instance) * 730\n      )\n    )\n  ) by (container)\n)\n"
    },
    {
     "expr": "topk(10,\n  sum(\n    (\n      sum(\n        container_memory_allocation_bytes{\n          cluster=\"$cluster\",\n          namespace=\"$namespace\"}\n      )\n      by (instance, container)\n      * on(instance) group_left()\n      (\n        avg(\n          node_ram_hourly_cost{\n            cluster=\"$cluster\"}\n        ) by (instance) / (1024 * 1024 * 1024) * 730\n      )\n    )\n    +\n    (\n      sum(\n        container_cpu_allocation{\n          cluster=\"$cluster\",\n          namespace=\"$namespace\"}\n      )\n      by (instance, container)\n      * on(instance) group_left()\n      (\n        avg(\n          node_cpu_hourly_cost{\n            cluster=\"$cluster\"}\n        ) by (instance) * 730\n      )\n    )\n  ) by (container)\n)\n\n/\ntopk(10,\n  sum(\n    (\n      sum(\n        container_memory_allocation_bytes{\n          cluster=\"$cluster\",\n          namespace=\"$namespace\"} offset 7d\n      )\n      by (instance, container)\n      * on(instance) group_left()\n      (\n        avg(\n          node_ram_hourly_cost{\n            cluster=\"$cluster\"} offset 7d\n        ) by (instance) / (1024 * 1024 * 1024) * 730\n      )\n    )\n    +\n    (\n      sum(\n        container_cpu_allocation{\n          cluster=\"$cluster\",\n          namespace=\"$namespace\"} offset 7d\n      )\n      by (instance, container)\n      * on(instance) group_left()\n      (\n        avg(\n          node_cpu_hourly_cost{\n            cluster=\"$cluster\"} offset 7d\n        ) by (instance) * 730\n      )\n    )\n  ) by (container)\n)\n\n* 100\n- 100\n"
    },
    {
     "expr": "topk(10,\n  sum(\n    (\n      sum(\n        container_memory_allocation_bytes{\n          cluster=\"$cluster\",\n          namespace=\"$namespace\"}\n      )\n      by (instance, container)\n      * on(instance) group_left()\n      (\n        avg(\n          node_ram_hourly_cost{\n            cluster=\"$cluster\"}\n        ) by (instance) / (1024 * 1024 * 1024) * 730\n      )\n    )\n    +\n    (\n      sum(\n        container_cpu_allocation{\n          cluster=\"$cluster\",\n          namespace=\"$namespace\"}\n      )\n      by (instance, container)\n      * on(instance) group_left()\n      (\n        avg(\n          node_cpu_hourly_cost{\n            cluster=\"$cluster\"}\n        ) by (instance) * 730\n      )\n    )\n  ) by (container)\n)\n\n/\ntopk(10,\n  sum(\n    (\n      sum(\n        container_memory_allocation_bytes{\n          cluster=\"$cluster\",\n          namespace=\"$namespace\"} offset 30d\n      )\n      by (instance, container)\n      * on(instance) group_left()\n      (\n        avg(\n          node_ram_hourly_cost{\n            cluster=\"$cluster\"} offset 30d\n        ) by (instance) / (1024 * 1024 * 1024) * 730\n      )\n    )\n    +\n    (\n      sum(\n        container_cpu_allocation{\n          cluster=\"$cluster\",\n          namespace=\"$namespace\"} offset 30d\n      )\n      by (instance, container)\n      * on(instance) group_left()\n      (\n        avg(\n          node_cpu_hourly_cost{\n            cluster=\"$cluster\"} offset 30d\n        ) by (instance) * 730\n      )\n    )\n  ) by (container)\n)\n\n* 100\n- 100\n"
    }
   ]
  },
  {
   "title": "Cost by Container",
   "type": "piechart",
   "description": "Shows the cost by container across the cluster.",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "topk(10,\n  sum(\n    (\n      sum(\n        container_memory_allocation_bytes{\n          cluster=\"$cluster\",\n          namespace=\"$namespace\"}\n      )\n      by (instance, container)\n      * on(instance) group_left()\n      (\n        avg(\n          node_ram_hourly_cost{\n            cluster=\"$cluster\"}\n        ) by (instance) / (1024 * 1024 * 1024) * 730\n      )\n    )\n    +\n    (\n      sum(\n        container_cpu_allocation{\n          cluster=\"$cluster\",\n          namespace=\"$namespace\"}\n      )\n      by (instance, container)\n      * on(instance) group_left()\n      (\n        avg(\n          node_cpu_hourly_cost{\n            cluster=\"$cluster\"}\n        ) by (instance) * 730\n      )\n    )\n  ) by (container)\n)\n",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  { "title": "PV Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Persistent Volumes Monthly Cost",
   "type": "table",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "sum(\n  sum(\n    kube_persistentvolume_capacity_bytes{\n      cluster=\"$cluster\"\n    } / (1024 * 1024 * 1024)\n  ) by (persistentvolume)\n  * on(persistentvolume) group_left(cluster, namespace)\n    label_replace(\n      kube_persistentvolumeclaim_info{\n        cluster=\"$cluster\",\n        namespace=\"$namespace\"\n      },\n      \"persistentvolume\", \"$1\",\n      \"volumename\", \"(.*)\"\n    )\n) by (persistentvolume)\n"
    },
    {
     "expr": "sum(\n  sum(\n    kube_persistentvolume_capacity_bytes{\n      cluster=\"$cluster\"\n    }\n    / (1024 * 1024 * 1024)\n  ) by (persistentvolume)\n  *\n  sum(\n    pv_hourly_cost{\n      cluster=\"$cluster\"\n    }\n  ) by (persistentvolume)\n  * on(persistentvolume) group_left(cluster, namespace) (\n    label_replace(\n      kube_persistentvolumeclaim_info{\n        cluster=\"$cluster\",\nnamespace=\"$namespace\"\n\n      },\n      \"persistentvolume\", \"$1\",\n      \"volumename\", \"(.*)\"\n    )\n  )\n) by (persistentvolume) * 730\n"
    }
   ]
  },
  {
   "title": "Cost by Persistent Volume",
   "type": "piechart",
   "description": "Shows the cost by persistent volume across the cluster.",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum(\n  sum(\n    kube_persistentvolume_capacity_bytes{\n      cluster=\"$cluster\"\n    }\n    / (1024 * 1024 * 1024)\n  ) by (persistentvolume)\n  *\n  sum(\n    pv_hourly_cost{\n      cluster=\"$cluster\"\n    }\n  ) by (persistentvolume)\n  * on(persistentvolume) group_left(cluster, namespace) (\n    label_replace(\n      kube_persistentvolumeclaim_info{\n        cluster=\"$cluster\",\nnamespace=\"$namespace\"\n\n      },\n      \"persistentvolume\", \"$1\",\n      \"volumename\", \"(.*)\"\n    )\n  )\n) by (persistentvolume) * 730\n",
     "legendFormat": "{{ persistentvolume }}"
    }
   ]
  }
 ]
}