---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  namespace: "linkerd-viz"
  name: "linkerd-viz"
spec:
  parentRefs:
  - namespace: kubenuts
    name: kubenuts-internal
    sectionName: https
  hostnames:
  - "linkerd-viz.pg02.narvar.qa"
  rules:
  - backendRefs:
    - name: web
      port: 8084
