---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  namespace: "telemetry"
  name: "telemetry"
spec:
  provider:
    aws:
      service: SecretsManager
      region: "us-west-2"
      auth:
        jwt:
          serviceAccountRef:
            name: "telemetry-secret-store"
