# External Secrets Operator is a Kubernetes operator that integrates external secret management
# systems like AWS Secrets Manager, HashiCorp Vault, etc.
# Re: https://external-secrets.io/latest/
metadata:
  name: external-secrets
  version: "2.9.0"
  namespace: kubenuts

# Properties that can be customized to suit your system needs.
properties:
  # -- Resources to provide to the operator pod
  resources: {}
    # requests:
    #   cpu: 50m
    #   memory: 100Mi
    # limits:
    #   cpu: 100m
    #   memory: 200Mi
