# Kubenutty core components.
metadata:
  name: kubenuts
  version: 0.1.0
  namespace: kubenuts
  required: true

properties:
  # Internal gateway configuration.
  internalGateway:
    # -- Enable the HTTP redirect route on the internal gateway
    httpRedirectEnabled: true

  # External gateway configuration.
  externalGateway:
    # -- Enable the external gateway and its associated resources
    enabled: false
    # -- Override the GatewayClass name. Defaults to alb (EKS), gke-l7-global-external-managed (GKE).
    gatewayClassName: ""
    # -- Enable the HTTP redirect route on the external gateway
    httpRedirectEnabled: true

  # -- Additional namespaces to create. A SecretStore will also be created for each namespace.
  extraNamespaces: []
