# Linkerd service mesh.
# Re: https://linkerd.io/
metadata:
  name: linkerd
  version: "2.20.0"
  namespace: linkerd

# Properties that can be customized to suit your system needs.
properties:
  # Buoyant Enterprise for Linkerd (BEL) configuration.
  enterpriseEdition:
    # -- Set to true to run BEL. NOTE You may need to purchase licenses depending on the size of
    # your organization and your specific use cases. If licenses are required, you will need to
    # purchase and renew them yourself (KubeNutty is not responsible for the licenses). For more
    # information:
    #
    # - [BEL Plans and Pricing](https://buoyant.io/pricing)
    # - [BEL Overview](https://docs.buoyant.io/buoyant-enterprise-linkerd/latest/overview/)
    #
    # Default to false to run open source Linkerd (no license required)
    enabled: true

  # -- The number of replicas for each control plane pod
  controllerReplicas: 1

  proxy:
    # -- Resources to provide to each proxy container
    resources:
      requests:
        cpu: 50m
      #   memory: 100Mi
      # limits:
      #   memory: 200Mi

  destination:
    # -- Resources to provide to each destination container.
    resources:
      requests:
        cpu: 50m

  heartbeat:
    # -- Resources to provide to each heartbeat container.
    resources: {}

  identity:
    # -- Resources to provide to the identity controller.
    resources:
      requests:
        cpu: 50m

  policyController:
    # -- Resources to provide to the policy controller.
    resources:
      requests:
        cpu: 50m

  proxyInjector:
    # -- Resources to provide to the proxy injector.
    resources:
      requests:
        cpu: 50m

  spValidator:
    # -- Resources to provide to the SP validator.
    resources:
      requests:
        cpu: 50m
