---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- opencost-dashboards.yaml
- opencost-helm-release.yaml
- opencost-helm-repository.yaml
- opencost-helm-values.yaml
- opencost-secrets.yaml
