---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  namespace: "telemetry"
  name: "opencost-secrets"
spec:
  interval: 10m
  prune: true
  sourceRef:
    kind: GitRepository
    namespace: flux-system
    name: flux-system
  path: "/manifests/opencost/opencost-secrets"
  targetNamespace: "telemetry"
  healthChecks:
  - apiVersion: v1
    kind: Secret
    namespace: "telemetry"
    name: "opencost-cloud-integration"
