---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  namespace: "argocd"
  name: "argocd"
spec:
  provider:
    aws:
      service: SecretsManager
      region: "us-west-2"
      auth:
        jwt:
          serviceAccountRef:
            name: "argocd-secret-store"
