---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  namespace: "telemetry"
  name: "kube-state-metrics"
spec:
  interval: 30m
  timeout: 15m
  releaseName: "kube-state-metrics"
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        namespace: "telemetry"
        name: "kube-state-metrics"
      chart: kube-state-metrics
      version: "8.4.1"
  install:
    remediation:
      retries: 10
  upgrade:
    remediation:
      retries: 10
  valuesFrom:
  - kind: ConfigMap
    name: "kube-state-metrics-helm-values"
    valuesKey: values.yaml
