---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  namespace: "kubenuts"
  name: "kubenuts"
spec:
  provider:
    aws:
      service: SecretsManager
      region: "us-west-2"
      auth:
        jwt:
          serviceAccountRef:
            name: "kubenuts-secret-store"
