---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  namespace: "telemetry"
  name: "grafana"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: "telemetry"
  target:
    name: "grafana"
    creationPolicy: Owner
  data:
  - secretKey: adminUser
    remoteRef:
      key: "pg02/telemetry/grafana"
      property: admin-user
  - secretKey: adminPassword
    remoteRef:
      key: "pg02/telemetry/grafana"
      property: admin-password
