---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: "kubenuts"
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: "external-dns-helm-values"
  files:
  - values.yaml
