---
provider:
  name: aws
domainFilters:
- "pg02.narvar.qa"
logFormat: json
logLevel: warning
policy: sync
serviceAccount:
  create: true
  name: "external-dns"
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::472882997329:role/pg02-external-dns"
sources:
- gateway-httproute
- ingress
- service
txtOwnerId: "kubenuts@pg02"
