---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  namespace: "kubenuts"
  name: "weave-gitops"
spec:
  parentRefs:
  - namespace: kubenuts
    name: kubenuts-internal
    sectionName: https
  hostnames:
  - "fluxcd.pg02.narvar.qa"
  rules:
  - backendRefs:
    - name: "weave-gitops"
      port: 9001
