---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  namespace: "victoria-logs"
  name: "victoria-logs-collector-helm-release"
spec:
  dependsOn:
  - namespace: "victoria-logs"
    name: "victoria-logs-collector-helm-values"
  - namespace: "victoria-logs"
    name: "victoria-logs-cluster-helm-release"
  interval: 10m
  prune: true
  sourceRef:
    kind: GitRepository
    namespace: flux-system
    name: flux-system
  path: "/manifests/victoria-logs/victoria-logs-collector-helm-release"
  targetNamespace: "victoria-logs"
  healthChecks:
  - apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    namespace: "victoria-logs"
    name: "victoria-logs-collector"
