---
nameOverride: node-exporter
extraArgs:
  - --collector.filesystem.mount-points-exclude=^/(dev|proc|run/containerd/.+|sys|var/lib/docker/.+|var/lib/kubelet/.+)($|/)
  - --collector.filesystem.fs-types-exclude=^(autofs|binfmt_misc|bpf|cgroup2?|configfs|debugfs|devpts|devtmpfs|efivarfs|fusectl|hugetlbfs|iso9660|mqueue|nsfs|overlay|proc|procfs|pstore|ramfs|rpc_pipefs|securityfs|selinuxfs|squashfs|erofs|sysfs|tmpfs|tracefs)$
livenessProbe:
  timeoutSeconds: 3
readinessProbe:
  timeoutSeconds: 3
prometheus:
  monitor:
    enabled: true
    jobLabel: jobLabel
    relabelings:
    - sourceLabels:
      - __meta_kubernetes_pod_node_name
      targetLabel: node
    metricRelabelings:
    - action: drop
      regex: /var/lib/kubelet/pods.+
      sourceLabels:
      - mountpoint
service:
  labels:
    jobLabel: node-exporter
