---
nameOverride: node-exporter
extraArgs:
  - --collector.filesystem.mount-points-exclude=^/(dev|proc|sys|var/lib/docker/.+|var/lib/kubelet/.+)($|/)
  - --collector.filesystem.fs-types-exclude=^(autofs|binfmt_misc|bpf|cgroup2?|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|iso9660|mqueue|nsfs|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|selinuxfs|squashfs|erofs|sysfs|tracefs)$
prometheus:
  monitor:
    enabled: true
    jobLabel: jobLabel
    metricRelabelings:
    - action: drop
      regex: /var/lib/kubelet/pods.+
      sourceLabels:
      - mountpoint
service:
  labels:
    jobLabel: node-exporter
