---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: "victoria-metrics"
  name: "victoria-metrics-grafana-datasource"
  labels:
    app.kubernetes.io/instance: "victoria-metrics"
    app.kubernetes.io/name: "victoria-metrics-grafana-datasource"
    kubenuts/grafana: datasource
    grafana_datasource: "1"
data:
  victoria-metrics.yaml: |
    apiVersion: 1
    datasources:
    - name: VictoriaMetrics
      type: prometheus
      url: http://vmauth-victoria-metrics.victoria-metrics:8427/select/0/prometheus
      access: proxy
      isDefault: true
      jsonData:
        httpMethod: POST
        prometheusType: VictoriaMetrics
        timeInterval: 20s
